server:
  servlet:
    context-path: /modyo

spring.mvc.throw-exception-if-no-handler-found: true
spring.resources.add-mappings: false

poke-api:
  url: https://pokeapi.co/api/v2
  methods:
    get-poke: /pokemon
    get-species: /pokemon-species
    get-evolution: /evolution-chain